const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
// intro, once per tab
const intro=$('#intro');
if(sessionStorage.getItem('ak_intro')) intro.remove();
else{sessionStorage.setItem('ak_intro','1');setTimeout(()=>intro.classList.add('hide'),2200);setTimeout(()=>intro.remove(),2900)}
// subtle network background
function net(canvas, introMode=false){if(!canvas)return;const ctx=canvas.getContext('2d');let pts=[];function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);pts=Array.from({length:introMode?34:22},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.08,vy:(Math.random()-.5)*.08}))}function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const p of pts){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>innerWidth)p.vx*=-1;if(p.y<0||p.y>innerHeight)p.vy*=-1;ctx.fillStyle=introMode?'rgba(69,217,232,.55)':'rgba(69,217,232,.26)';ctx.fillRect(p.x,p.y,2,2)}for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){let a=pts[i],b=pts[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<160){ctx.strokeStyle=`rgba(69,217,232,${(1-d/160)*(introMode?.12:.045)})`;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}requestAnimationFrame(draw)}resize();addEventListener('resize',resize);draw()}net($('#networkBg'));net($('#introNet'),true);
// Aegis explorer
const layers={
firewall:{k:'COUCHE 01 / PÉRIMÈTRE',t:'Pare-feu & routage',p:"OPNsense constitue la passerelle du lab. Il permet de travailler le filtrage des flux, les règles réseau et la séparation des zones.",d:['Internet','OPNsense','LAN / zones']},
ad:{k:'COUCHE 02 / IDENTITÉ',t:'Active Directory Domain Services',p:"Windows Server 2022 porte le domaine du laboratoire : comptes, droits, services d'annuaire et administration centralisée.",d:['Windows Server','AD DS','Clients domaine']},
network:{k:'COUCHE 03 / SERVICES',t:'DNS & DHCP',p:"Les services DNS et DHCP accompagnent le domaine afin de fournir résolution de noms et configuration réseau aux postes du lab.",d:['DNS','DHCP','Clients']},
segment:{k:'COUCHE 04 / SEGMENTATION',t:'Segmentation & contrôle des flux',p:"Le laboratoire sert à pratiquer la séparation logique des environnements et le contrôle des communications entre zones.",d:['Zone utilisateurs','ACL / règles','Zone serveurs']},
linux:{k:'COUCHE 05 / SYSTÈMES',t:'Serveur Debian 12',p:"Une machine Linux complète l'environnement Windows pour travailler l'administration, les services et l'automatisation.",d:['Debian 12','systemd','Bash']},
monitor:{k:'COUCHE 06 / SUPERVISION',t:'Supervision & alertes',p:"La couche de supervision permet de centraliser l'état des hôtes et services et de travailler sur les alertes et le maintien en condition opérationnelle.",d:['Agents','Zabbix','Alertes']}
};function showLayer(k){const x=layers[k];$('#layerPanel').innerHTML=`<small>${x.k}</small><h3>${x.t}</h3><p>${x.p}</p><div class="diagram">${x.d.map((v,i)=>`${i?'<i>→</i>':''}<span>${v}</span>`).join('')}</div>`}showLayer('firewall');$$('#layers button').forEach(b=>b.onclick=()=>{$$('#layers button').forEach(x=>x.classList.remove('active'));b.classList.add('active');showLayer(b.dataset.k)});
// terminal
const responses={help:'Commandes : whoami · skills · experience · formation · aegis · contact · clear',whoami:'Alexandre Kiefer — Administrateur Systèmes, Réseaux & Cybersécurité junior.',skills:'Windows Server · Active Directory · Debian · VMware · VLAN/ACL · VPN · OPNsense · Zabbix · Synology · Bash · PowerShell',experience:'Kertios : stage 3 mois | CESAM SEED : environ 1 an en alternance.',formation:'TP Technicien Informatique (2024) · Bachelor AIS (2025) · objectif Mastère Expert Cybersécurité.',aegis:'Aegis Infra Lab : OPNsense + Windows Server 2022 + AD/DNS/DHCP + Debian + segmentation + supervision.',contact:'Kiefer.alexandre1@gmail.com · 06 28 04 15 78'};$('#termForm').onsubmit=e=>{e.preventDefault();let v=$('#termInput').value.trim().toLowerCase();if(!v)return false;if(v==='clear'){$('#termOut').innerHTML='';$('#termInput').value='';return false}$('#termOut').insertAdjacentHTML('beforeend',`<p><b>alexandre@portfolio:~$</b> ${v}</p><p>${responses[v]||'Commande inconnue. Tape help.'}</p>`);$('#termInput').value='';$('#termOut').scrollTop=$('#termOut').scrollHeight;return false};
